name: videomeet
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2

  # Service Locator (for dependency injection)
  get_it: ^7.6.0
  # Networking
  dio: ^5.4.3+1

  # Value Equality (for entities)
  equatable: ^2.0.5
  either_dart: ^0.1.0
  connectivity_plus: ^4.0.2
  
  # Offline Caching
  shared_preferences: ^2.2.1
  http: ^0.13.6

  # --- VIDEO SDK (CORE) ---
  agora_rtc_engine: 6.1.0  
  permission_handler: ^10.4.3
  # -------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png" 
  min_sdk_android: 21
  remove_alpha_ios: true 
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

